[project]
name = "rosarl"
description = "ROSARL project"
version = "0.1.0"
authors = [
    { name = "Mark Nemecek", email = "mark.nemecek@duke.edu" }
]
dependencies = [
    "omnisafe",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["rosarl"]
