from typing import ClassVar

from omnisafe.envs.core import env_register
from omnisafe.envs.safety_gymnasium_env import SafetyGymnasiumEnv


@env_register
class SafetyterminalGymnasiumEnv(SafetyGymnasiumEnv):
    _support_envs: ClassVar[list[str]] = [
        'SafetyterminalPointGoal0-v0',
        'SafetyterminalPointGoal1-v0',
        'SafetyterminalPointGoal2-v0',
        'SafetyterminalPointButton0-v0',
        'SafetyterminalPointButton1-v0',
        'SafetyterminalPointButton2-v0',
        'SafetyterminalPointPush0-v0',
        'SafetyterminalPointPush1-v0',
        'SafetyterminalPointPush2-v0',
        'SafetyterminalPointCircle0-v0',
        'SafetyterminalPointCircle1-v0',
        'SafetyterminalPointCircle2-v0',
        'SafetyterminalCarGoal0-v0',
        'SafetyterminalCarGoal1-v0',
        'SafetyterminalCarGoal2-v0',
        'SafetyterminalCarButton0-v0',
        'SafetyterminalCarButton1-v0',
        'SafetyterminalCarButton2-v0',
        'SafetyterminalCarPush0-v0',
        'SafetyterminalCarPush1-v0',
        'SafetyterminalCarPush2-v0',
        'SafetyterminalCarCircle0-v0',
        'SafetyterminalCarCircle1-v0',
        'SafetyterminalCarCircle2-v0',
        'SafetyterminalAntGoal0-v0',
        'SafetyterminalAntGoal1-v0',
        'SafetyterminalAntGoal2-v0',
        'SafetyterminalAntButton0-v0',
        'SafetyterminalAntButton1-v0',
        'SafetyterminalAntButton2-v0',
        'SafetyterminalAntPush0-v0',
        'SafetyterminalAntPush1-v0',
        'SafetyterminalAntPush2-v0',
        'SafetyterminalAntCircle0-v0',
        'SafetyterminalAntCircle1-v0',
        'SafetyterminalAntCircle2-v0',
        'SafetyterminalDoggoGoal0-v0',
        'SafetyterminalDoggoGoal1-v0',
        'SafetyterminalDoggoGoal2-v0',
        'SafetyterminalDoggoButton0-v0',
        'SafetyterminalDoggoButton1-v0',
        'SafetyterminalDoggoButton2-v0',
        'SafetyterminalDoggoPush0-v0',
        'SafetyterminalDoggoPush1-v0',
        'SafetyterminalDoggoPush2-v0',
        'SafetyterminalDoggoCircle0-v0',
        'SafetyterminalDoggoCircle1-v0',
        'SafetyterminalDoggoCircle2-v0',
        'SafetyterminalRacecarGoal0-v0',
        'SafetyterminalRacecarGoal1-v0',
        'SafetyterminalRacecarGoal2-v0',
        'SafetyterminalRacecarButton0-v0',
        'SafetyterminalRacecarButton1-v0',
        'SafetyterminalRacecarButton2-v0',
        'SafetyterminalRacecarPush0-v0',
        'SafetyterminalRacecarPush1-v0',
        'SafetyterminalRacecarPush2-v0',
        'SafetyterminalRacecarCircle0-v0',
        'SafetyterminalRacecarCircle1-v0',
        'SafetyterminalRacecarCircle2-v0',
        # 'SafetyterminalHalfCheetahVelocity-v1',
        # 'SafetyterminalHopperVelocity-v1',
        # 'SafetyterminalSwimmerVelocity-v1',
        # 'SafetyterminalWalker2dVelocity-v1',
        # 'SafetyterminalAntVelocity-v1',
        # 'SafetyterminalHumanoidVelocity-v1',
        # 'SafetyterminalPointRun0-v0',
        # 'SafetyterminalCarRun0-v0',
    ]
