from typing import ClassVar

from omnisafe.envs.core import env_register
from omnisafe.envs.safety_gymnasium_env import SafetyGymnasiumEnv


@env_register
class SafetyterminalGymnasiumEnv(SafetyGymnasiumEnv):
    _support_envs: ClassVar[list[str]] = [
        'SafetyterminalPointGoal0-v0',
        'SafetyterminalPointGoal1-v0',
        'SafetyterminalPointGoal2-v0',
        'SafetyterminalPointButton0-v0',
        'SafetyterminalPointButton1-v0',
        'SafetyterminalPointButton2-v0',
        'SafetyterminalPointPush0-v0',
        'SafetyterminalPointPush1-v0',
        'SafetyterminalPointPush2-v0',
        'SafetyterminalPointCircle0-v0',
        'SafetyterminalPointCircle1-v0',
        'SafetyterminalPointCircle2-v0',
        'SafetyterminalCarGoal0-v0',
        'SafetyterminalCarGoal1-v0',
        'SafetyterminalCarGoal2-v0',
        'SafetyterminalCarButton0-v0',
        'SafetyterminalCarButton1-v0',
        'SafetyterminalCarButton2-v0',
        'SafetyterminalCarPush0-v0',
        'SafetyterminalCarPush1-v0',
        'SafetyterminalCarPush2-v0',
        'SafetyterminalCarCircle0-v0',
        'SafetyterminalCarCircle1-v0',
        'SafetyterminalCarCircle2-v0',
        'SafetyterminalAntGoal0-v0',
        'SafetyterminalAntGoal1-v0',
        'SafetyterminalAntGoal2-v0',
        'SafetyterminalAntButton0-v0',
        'SafetyterminalAntButton1-v0',
        'SafetyterminalAntButton2-v0',
        'SafetyterminalAntPush0-v0',
        'SafetyterminalAntPush1-v0',
        'SafetyterminalAntPush2-v0',
        'SafetyterminalAntCircle0-v0',
        'SafetyterminalAntCircle1-v0',
        'SafetyterminalAntCircle2-v0',
        'SafetyterminalDoggoGoal0-v0',
        'SafetyterminalDoggoGoal1-v0',
        'SafetyterminalDoggoGoal2-v0',
        'SafetyterminalDoggoButton0-v0',
        'SafetyterminalDoggoButton1-v0',
        'SafetyterminalDoggoButton2-v0',
        'SafetyterminalDoggoPush0-v0',
        'SafetyterminalDoggoPush1-v0',
        'SafetyterminalDoggoPush2-v0',
        'SafetyterminalDoggoCircle0-v0',
        'SafetyterminalDoggoCircle1-v0',
        'SafetyterminalDoggoCircle2-v0',
        'SafetyterminalRacecarGoal0-v0',
        'SafetyterminalRacecarGoal1-v0',
        'SafetyterminalRacecarGoal2-v0',
        'SafetyterminalRacecarButton0-v0',
        'SafetyterminalRacecarButton1-v0',
        'SafetyterminalRacecarButton2-v0',
        'SafetyterminalRacecarPush0-v0',
        'SafetyterminalRacecarPush1-v0',
        'SafetyterminalRacecarPush2-v0',
        'SafetyterminalRacecarCircle0-v0',
        'SafetyterminalRacecarCircle1-v0',
        'SafetyterminalRacecarCircle2-v0',
        # 'SafetyterminalHalfCheetahVelocity-v1',
        # 'SafetyterminalHopperVelocity-v1',
        # 'SafetyterminalSwimmerVelocity-v1',
        # 'SafetyterminalWalker2dVelocity-v1',
        # 'SafetyterminalAntVelocity-v1',
        # 'SafetyterminalHumanoidVelocity-v1',
        # 'SafetyterminalPointRun0-v0',
        # 'SafetyterminalCarRun0-v0',
        'SafetyterminalgoalPointGoal0-v0',
        'SafetyterminalgoalPointGoal1-v0',
        'SafetyterminalgoalPointGoal2-v0',
        'SafetyterminalgoalPointButton0-v0',
        'SafetyterminalgoalPointButton1-v0',
        'SafetyterminalgoalPointButton2-v0',
        'SafetyterminalgoalPointPush0-v0',
        'SafetyterminalgoalPointPush1-v0',
        'SafetyterminalgoalPointPush2-v0',
        'SafetyterminalgoalPointCircle0-v0',
        'SafetyterminalgoalPointCircle1-v0',
        'SafetyterminalgoalPointCircle2-v0',
        'SafetyterminalgoalCarGoal0-v0',
        'SafetyterminalgoalCarGoal1-v0',
        'SafetyterminalgoalCarGoal2-v0',
        'SafetyterminalgoalCarButton0-v0',
        'SafetyterminalgoalCarButton1-v0',
        'SafetyterminalgoalCarButton2-v0',
        'SafetyterminalgoalCarPush0-v0',
        'SafetyterminalgoalCarPush1-v0',
        'SafetyterminalgoalCarPush2-v0',
        'SafetyterminalgoalCarCircle0-v0',
        'SafetyterminalgoalCarCircle1-v0',
        'SafetyterminalgoalCarCircle2-v0',
        'SafetyterminalgoalAntGoal0-v0',
        'SafetyterminalgoalAntGoal1-v0',
        'SafetyterminalgoalAntGoal2-v0',
        'SafetyterminalgoalAntButton0-v0',
        'SafetyterminalgoalAntButton1-v0',
        'SafetyterminalgoalAntButton2-v0',
        'SafetyterminalgoalAntPush0-v0',
        'SafetyterminalgoalAntPush1-v0',
        'SafetyterminalgoalAntPush2-v0',
        'SafetyterminalgoalAntCircle0-v0',
        'SafetyterminalgoalAntCircle1-v0',
        'SafetyterminalgoalAntCircle2-v0',
        'SafetyterminalgoalDoggoGoal0-v0',
        'SafetyterminalgoalDoggoGoal1-v0',
        'SafetyterminalgoalDoggoGoal2-v0',
        'SafetyterminalgoalDoggoButton0-v0',
        'SafetyterminalgoalDoggoButton1-v0',
        'SafetyterminalgoalDoggoButton2-v0',
        'SafetyterminalgoalDoggoPush0-v0',
        'SafetyterminalgoalDoggoPush1-v0',
        'SafetyterminalgoalDoggoPush2-v0',
        'SafetyterminalgoalDoggoCircle0-v0',
        'SafetyterminalgoalDoggoCircle1-v0',
        'SafetyterminalgoalDoggoCircle2-v0',
        'SafetyterminalgoalRacecarGoal0-v0',
        'SafetyterminalgoalRacecarGoal1-v0',
        'SafetyterminalgoalRacecarGoal2-v0',
        'SafetyterminalgoalRacecarButton0-v0',
        'SafetyterminalgoalRacecarButton1-v0',
        'SafetyterminalgoalRacecarButton2-v0',
        'SafetyterminalgoalRacecarPush0-v0',
        'SafetyterminalgoalRacecarPush1-v0',
        'SafetyterminalgoalRacecarPush2-v0',
        'SafetyterminalgoalRacecarCircle0-v0',
        'SafetyterminalgoalRacecarCircle1-v0',
        'SafetyterminalgoalRacecarCircle2-v0',
        # 'SafetyterminalgoalHalfCheetahVelocity-v1',
        # 'SafetyterminalgoalHopperVelocity-v1',
        # 'SafetyterminalgoalSwimmerVelocity-v1',
        # 'SafetyterminalgoalWalker2dVelocity-v1',
        # 'SafetyterminalgoalAntVelocity-v1',
        # 'SafetyterminalgoalHumanoidVelocity-v1',
        # 'SafetyterminalgoalPointRun0-v0',
        # 'SafetyterminalgoalCarRun0-v0',
    ]
